package:
  name: metawrap-mg
  version: "1.3.2"

source:
  git_url: https://github.com/bxlab/metaWRAP.git

requirements:
  build:

  run:
    - biopython 1.68
    - blas 2.5 mkl
    - blast 2.6.0
    - bmtagger 3.101
    - bowtie2 2.3.5
    - bwa 0.7.17
    - checkm-genome 1.0.12
    - concoct 1.0.0
    - fastqc 0.11.8
    - kraken 1.1
    - kraken2 2.0
    - krona 2.7
    - matplotlib 2.2.3
    - maxbin2 2.2.6
    - megahit 1.1.3
    - metabat2 2.12.1
    - openssl 1.0
    - pandas 0.24.2
    - perl-bioperl
    - pplacer 1.1.alpha19
    - prokka 1.*
    - quast 5.0.2
    - r-ggplot2 3.1.0
    - r-reshape2
    - r-recommended 3.5.1
    - salmon 0.13.1
    - samtools 1.9
    - seaborn 0.9.0
    - spades 3.13.0
    - taxator-tk 1.3.3e
    - trim-galore 0.5.0

about:
  home: https://github.com/ursky/metaWRAP
  license: MIT
  license_file: LICENSE

